apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc-trading-app
  labels:
    app: btc-trading-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: btc-trading-app
  template:
    metadata:
      labels:
        app: btc-trading-app
    spec:
      containers:
      - name: btc-trading-app
        image: gcr.io/llm-trading-henry2024/btc-trading-app:btc-v1.0
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: ALPACA_API_KEY
          valueFrom:
            secretKeyRef:
              name: trading-secrets
              key: alpaca-api-key
        - name: ALPACA_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: trading-secrets
              key: alpaca-secret-key
        - name: NEWS_API_KEY
          valueFrom:
            secretKeyRef:
              name: trading-secrets
              key: news-api-key
        - name: COHERE_KEY
          valueFrom:
            secretKeyRef:
              name: trading-secrets
              key: cohere-key
        livenessProbe:
          httpGet:
            path: /test_apis
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /test_apis
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: btc-trading-service
  labels:
    app: btc-trading-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: btc-trading-app 